export const LOADING = 'CART/LOADING';
export const SUCCESS = 'CART/SUCCESS';
export const ERROR = 'CART/ERROR';
export const GET_ALL_CART_PRODUCTS = 'CART/GET_ALL_CART_PRODUCTS';
export const ADD_ITEMS_TO_CART = 'CART/ADD_ITEMS_TO_CART';
export const UPDATE_QUANTITY_IN_CART = 'CART/UPDATE_QUANTITY_IN_CART';
export const DELETE_PRODUCT_FROM_CART = 'CART/DELETE_PRODUCT_FROM_CART';
export const ADD_ITEMS_IN_PURCHASED_LIST = 'CART/ADD_ITEMS_IN_PURCHASED_LIST';