export const GET_ALL_ORDERS_RELATED_DATA = 'ADMIN/GET_ALL_ORDERS_RELATED_DATA'
export const GET_FILTERED_PURCHASED_PRODUCTS = 'ADMIN/GET_FILTERED_PURCHASED_PRODUCTS'
export const ADD_NEW_PRODUCT = 'ADMIN/ADD_NEW_PRODUCT'
export const FILTER_ORDERS = 'ADMIN/FILTER_ORDERS'
